name: wallpaper_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.5.2+7

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.1
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  change_app_package_name: ^1.1.0
  shared_preferences: ^2.0.17
  internet_connection_checker: ^1.0.0+1
  flutter_native_splash: ^2.2.16
  bloc: ^8.1.1
  path_provider: ^2.0.14
  sqflite: ^2.2.8
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

# flutter_native_splash
flutter_native_splash:
  color: "#673AB7"
  image: assets/images/splash.png
  fill: true
  fullscreen: true
  android: true
  ios: true
  web: true

#flutter_icons
flutter_icons:
  android: true
  image_path: "assets/images/icon.png"
  ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
   # - assets/json/
    #- assets/svg/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf